# Some convenient links:
# - https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md
#

name: CI-windows

on: [push,pull_request]

permissions:
  contents: read

defaults:
  run:
    shell: cmd
    
jobs:

  build:
    strategy:
      matrix:
        os: [windows-2022, windows-2025]
        config: [Release, Debug]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup msbuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          check-latest: true

      - name: Install missing Python packages
        run: |
          python -m pip install pip --upgrade || exit /b !errorlevel!
          python -m pip install pytest || exit /b !errorlevel!

      - name: Run CMake
        run: |
          cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_COMPILE_WARNING_AS_ERROR=On . || exit /b !errorlevel!

      - name: Build
        run: |
           msbuild -m simplecpp.sln /p:Configuration=${{ matrix.config }} /p:Platform=x64 || exit /b !errorlevel!
           
      - name: Test
        run: |
          .\${{ matrix.config }}\testrunner.exe || exit /b !errorlevel!

      - name: Selfcheck
        run: |
          .\${{ matrix.config }}\simplecpp.exe simplecpp.cpp -e || exit /b !errorlevel!

      - name: integration test
        run: |
          set SIMPLECPP_EXE_PATH=.\${{ matrix.config }}\simplecpp.exe
          python -m pytest integration_test.py -vv || exit /b !errorlevel!
        
